### ISSUE TITLE
Occasional crash on startup

### ISSUE THREAD

**Issue by riskable** [Fuzss/airhop#4]
It doesn't happen _all_ the time but occasionally when starting up Minecraft with the Airhop mod enabled it'll crash with the following:

```
[m[1;31m[10:24:51] [Server-Worker-4/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2117/1574257199@1f80c55e
java.lang.NullPointerException
	at com.fuzs.airhop.enchantment.AirHopEnchantments.onModConfig(AirHopEnchantments.java:32)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:66)
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$5(ModContainer.java:147)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:147)
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:89)
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:106)
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062)
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83)
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:154)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$startModLoading$6(ClientModLoader.java:123)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113)
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[m[1;31m[10:24:54] [Render thread/FATAL] [minecraft/Minecraft]: Reported exception thrown!
net.minecraft.crash.ReportedException: Rendering overlay
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:476) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:block_manipulation.MixinGameRenderer_B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:far_scenery.MixinGameRenderer_F,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:block_manipulation.MixinMinecraftClient_B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:block_manipulation.MixinMinecraftClient_B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[minecraft-1.15.2-client.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.2.2-launcher.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:39) [ForgeWrapper-1.4.1.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
Caused by: java.lang.NullPointerException
	at com.fuzs.airhop.enchantment.AirHopEnchantments.onModConfig(AirHopEnchantments.java:32) ~[?:1.2] {re:classloading,pl:object_holder_definalize:A}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:66) ~[?:31.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$5(ModContainer.java:147) ~[?:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_101] {}
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:147) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:89) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:106) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[?:?] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_101] {}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062) ~[?:1.8.0_101] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:154) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$startModLoading$6(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_101] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_101] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_101] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_101] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_101] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_101] {}
[m[32m[10:24:54] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:103]: ---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 5/28/20 10:24 AM
Description: Rendering overlay
```
(The full log has been uploaded here if you need it: https://paste.ee/p/t0GDv)

Upon relaunching Minecraft the problem always seems to go away.  As in, it never repeats itself twice in a row.  It's also most likely to happen after setting up a new modpack (as in, I just created the instance in MultiMC).  Very strange--never had a bug like this one before.

**Comment by Fuzss** [comment]
Should be fixed in f2e795b
